version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file :
      - .env
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks :
      - mynetwork

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file :
      - .env
    expose:
      - "9000"
    volumes:
      - wp:/var/www/html/wordpress
    restart: always
    networks :
      - mynetwork
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks :
      - mynetwork

networks:
  mynetwork:
    driver : bridge

volumes:
  wp:
    driver_opts:
      o: bind
      type: none
      device: /home/nouakhro/data/wordpress
  db:
    driver_opts:
      o: bind
      type: none
      device: /home/nouakhro/data/database