version: "3.8"

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    restart: always
  wordpress:
    build: ./wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/html
    ports:
      - "9000:9000"
    restart: always
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - "443:443"
    restart: always
volumes:
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nouakhro/inception/DATA/wp
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nouakhro/inception/DATA/db