version: "3"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./html:/var/www/html
    ports:
      - "443:443"
    restart: always
  mariadb:
    build: ./mariadb
    container_name: mariadb
    # volumes:
    #   - ./html:/var/www/html
    # ports:
    #   - "443:443"
    restart: always
