version: "3.8"

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      DATABASE_NAME : ${DATABASE_NAME}
      DATABASE_USER : ${DATABASE_USER}
      DATABASE_PASSWORD : ${DATABASE_PASSWORD}
      DATABASE_HOST : ${DATABASE_HOST}
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks :
      - mynetwork

  wordpress:
    build: ./wordpress
    container_name: wordpress
    environment:
      DATABASE_NAME : ${DATABASE_NAME}
      DATABASE_USER : ${DATABASE_USER}
      DATABASE_PASSWORD : ${DATABASE_PASSWORD}
      DATABASE_HOST : ${DATABASE_HOST}
      WORDPRESS_USER_NAME : ${WORDPRESS_USER_NAME}
      WORDPRESS_USER_PASSWORD : ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_USER_EMAIL : ${WORDPRESS_USER_EMAIL}
      WORDPRESS_ADMIM_NAME : ${WORDPRESS_ADMIM_NAME}
      WORDPRESS_ADMIM_EMAIL : ${WORDPRESS_ADMIM_EMAIL}
      WORDPRESS_ADMIM_PASSWORD : ${WORDPRESS_ADMIM_PASSWORD}
      WORDPRESS_URL : ${WORDPRESS_URL}
      WORDPRESS_TITLE : ${WORDPRESS_TITLE}
      WORDPRESS_ROOT : ${WORDPRESS_ROOT}
      WORDPRESS_ROOT_PASSWORD : ${WORDPRESS_ROOT_PASSWORD}
      WORDPRESS_ROOT_EMAIL : ${WORDPRESS_ROOT_EMAIL}
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wp:/var/www/html/wordpress
    restart: always
    networks :
      - mynetwork

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks :
      - mynetwork

networks:
  mynetwork:
    driver : bridge

volumes:
  wp:
    driver_opts:
      o: bind
      type: none
      device: /home/nouakhro/data/wordpress
  db:
    driver_opts:
      o: bind
      type: none
      device: /home/nouakhro/data/database
